server:
  port: 8080

spring:
  application:
    name: student-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_management_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ywt123YWT

mybatis:
  configuration:
    map-underscore-to-camel-case: true

